- docs/contributing/community-slack.md
Rewriting the suggestion from @Vampire on Slack
> Incorporate Slack engagement recommendations from @Vampire

- mkdocs.yml
Previous location is for Develocity Actions
> Use proper source of GitHub Actions

- .devcontainer/requirements.txt
- mkdocs-dotorg.yml
- mkdocs.yml
> Add public roadmap to the community site

- docs/events/gsoc/2023/README.md
- docs/events/gsoc/2024/README.md
- docs/events/gsoc/2024/checkstyle-plugin.md
- docs/events/gsoc/2024/gradle-build-server-android.md
- docs/events/gsoc/2024/gradle-build-server-devx.md
- docs/events/gsoc/README.md
> Initialize GSoC 2024 pages

- docs/events/gsoc/README.md
> Add references to project channels and notes/recordings

- mkdocs.yml
We will re-establish them once there is a full list and not "Oleg's highlights" :)
> Disable Key projects until we reach consensus

- docs/events/README.md
Added Gradle Mentorship Program and Hacktoberfest to the list, plus some pointers
> Add more programs to the events page

- .github/release-drafter.yml
- .github/workflows/changelog.yml
Just making it more fancy and allowing to highlight major contributions beyond 1.0
> Add Release Drafter to generate content changelogs and attributions

- docs/cookbook/README.md
Based on the feedback from @pioterj
> Update the Gradle Cookbook summary

- docs/cookbook/README.md
- docs/cookbook/android/README.md
- docs/cookbook/kotlin/README.md
- mkdocs.yml
> Add Android and Kotlin chapters to the cookbook

- mkdocs.yml
> Use the brand dark color in background images

- docs/events/hacktoberfest/2024/README.md
- docs/events/hacktoberfest/README.md
> Add Hacktoberfest sign-up form

- docs/events/gsoc/2024/gradle-build-server-android.md
Updates:
- developer documentation section
- unit and integration test section
- visual improvements
> Project page update

- docs/events/gsoc/2024/gradle-build-server-android.md
Changed image markdown to html image tags
> Page fixes

- mkdocs.yml
> Add support for rendering emoji, checkboxes and tasklists in GitHub style

- docs/assets/css/gradle.css
- overrides/main.html
Also changes the style for the announcement
> Add the Developer survey announcement

- docs/contributing/spread-the-word.md
Link to YouTube channel was wrong
> Fix YT link

- docs/resources/social-media.md
> Add a Social Media page

- mkdocs.yml
- overrides/main.html
> Fix event banner

- docs/events/hacktoberfest/2024/README.md
> Hacktoberfest 2024 - Fix wording for the Config Cache project

- README.md
I have not touched this repo for quite a while, and there are some deviations from the actual community infrastructure state. Just some minor updates
> Cleanup the repo README.md

- docs/events/hacktoberfest/2024/README.md
> Add Issue query to the GradleUp projects

- docs/resources/README.md
> Resources: Fix the link to professional services, add Slack news

- docs/contributing/documentation/README.md
> Improve social media metadata for the "Contributing to Documentation" pages

- docs/contributing/community-slack.md
> Add #docs to the featured Slack channel

- .github/workflows/ci.yml
- .github/workflows/preview-cleanup.yml
- docs/CONTRIBUTING.md
> Enable previews of the community site

- .github/workflows/ci.yml
- .github/workflows/preview-cleanup.yml
Forgot to push changes in #122
> Refactor workflow variable names

- docs/surveys/developer-survey/README.md
Parks https://github.com/gradle/community/issues/20
> Update the 2024 Developer Survey Status

- .vscode/settings.json
- docs/events/gsoc/2024/README.md
- docs/events/gsoc/README.md
- mkdocs.yml
Just a quick-start to enable GSoC 2025.
For #199
> Initialize the GSoC 2025 landing

- .github/workflows/ci.yml
- .github/workflows/preview-cleanup.yml
Until #128 is solved, we need a temporary workaround
> Deploy previews only for local branches

- .vscode/settings.json
- docs/events/gsoc/README.md
> Add extra GSoC 2025 project ideas

- docs/events/gsoc/README.md
> GSoC 2025 - Add the code analysis project idea

- docs/events/README.md
> GSoC 2025 - Minor page updates

- README.md
- docs/events/gsoc/README.md
Added Slack badge for community documentation.
> Add Slack badge to README and GSoC

- docs/events/gsoc/2025/maven-central-publishing-with-new-api.md
> Fix the link rendering in the Maven Central publishing project page

- docs/events/gsoc/2025/README.md
> GSoC 2025 Archive -  Update heading level for Maven Central plugin section
